project:
  type: book
  output-dir: _docs

execute: 
  cache: false

book:
  version: 2026.02.18
  google-analytics: G-04FCCG1TK2
  title: IA para el Científico con Prisa
  subtitle: o "Notas de Ejecución y Reflexiones Sobre IA"
  author: George G. Vega Yon, Ph.D.
  language: es
  original-date: 2018-01-19
  date: 2026-02-18
  cover-image: img/book-cover.png
  cover-image-alt: 'Una imagen de IA generada con Bing: Dibuja una imagen de una red social. Incluye a una persona examinando la red y sosteniendo una laptop en una mano. La laptop debería tener el logo del lenguaje de programación R.'
  page-footer: IA para el Científico con Prisa - [https://ggvy.cl](https://ggvy.cl){target="_blank"}
  repo-url: https://github.com/gvegayon/book-ai
  repo-branch: master
  repo-subdir: 'es'
  repo-actions: [edit, source, issue]
  image: img/book-cover.png
  twitter-card:
    description: 'Este libro (en desarrollo) es una colección de notas y reflexiones sobre el uso de la IA para la ciencia (y otras cosas también). Incluye ejemplos usando herramientas comunes de IA, recomendaciones e incluso algo de programación usando bibliotecas modernas de IA.'
    creator: "@gvegayon"
  site-url: https://book-ai.ggvy.cl
  sharing: [twitter, linkedin]
  navbar:
    # background: light
    search: true

  chapters: 
    - index.qmd
    - 00-intro.qmd
    - 01-overview-of-ai.qmd
    - 02-writing-assistant.qmd
    - 03-programming-ai.qmd
    - 04-agentic-ai.qmd
    - 05-evaluating-writing.qmd
    - 06-programmatic-ai.qmd
  appendices:
    - references.qmd
    - news.qmd
  downloads:
  - pdf


bibliography: ../book.bib

biblio-style: apalike

format: 
  html:
    html-math-method: katex
    toc: true
    number-sections: false
    theme: cerulean
  pdf:
    geometry: 
      - top=1in
      - bottom=1in
      - left=1in
      - right=1in
    fontsize: 12pt
    fontenc: T1
    include-in-header: ../preamble.tex
    keep-tex: true
